### ISSUE TITLE
请问docker版如何启用warp ipv6?

### ISSUE THREAD

**Issue by ziyocc** [fscarmen/warp_unlock#11]
脚本改成加"-6"：
`docker run -dit --restart=always --name wgcf --sysctl net.ipv6.conf.all.disable_ipv6=0 --device /dev/net/tun --privileged --cap-add net_admin --cap-add sys_module --log-opt max-size=1m -v /lib/modules:/lib/modules -v $WGCF_DIR:$WGCF_DIR fscarmen/netflix_unlock:latest -6`

好像也没效果

**Comment by fscarmen** [comment]
在实践过程中，发现换 V4 解锁的概率高，V6换来换去都不行的，所以docker里的 WGCF 配置文件是 V4
要改需要去映射的目录 /etc/wireguard/wgcf.conf 改

**Comment by ziyocc** [comment]
原来是这样，谢谢大佬：）
