### ISSUE TITLE
NETFLIX新加坡解锁刷不出来了吗

### ISSUE THREAD

**Issue by fopiko** [fscarmen/warp_unlock#13]
用的docker方式

**Comment by fscarmen** [comment]
很有可能，现在亚太区很难刷出来，即使刷出来，也几小时失效。
但你可以通过以下两条指令判断换IP是否在运行
```
docker exec -it wgcf ps -T | grep warp_unlock  # 看到下面有数据的话，说话换IP程序正在运行
   96 root      0:00 bash /etc/wireguard/warp_unlock.sh
  439 root      0:00 bash /etc/wireguard/warp_unlock.sh

docker exec -it wgcf curl -s4m8 https://ip.gs # 查 docker 的IPv4
8.37.43.100

docker exec -it wgcf curl -s4m8 https://ip.gs # 隔20秒再按，看是否更换了IP
8.37.43.3
```

**Comment by fscarmen** [comment]
不知啥时候能恢复

**Comment by fscarmen** [comment]
好像CF新出来的 IP段 104.28.xxx.xxx 有戏哦

<img width="506" alt="image" src="https://user-images.githubusercontent.com/62703343/165716325-ec742f79-b36c-41e6-8565-055d607ac417.png">

**Comment by abc3660170** [comment]
弱弱的问一句，香港的机器能刷SG吗，我试了很久都没有，是因为机器在香港还是因为SG的本来就不好刷

**Comment by fscarmen** [comment]
> 弱弱的问一句，香港的机器能刷SG吗，我试了很久都没有，是因为机器在香港还是因为SG的本来就不好刷

现香港和新加坡，甚至整个亚太区都不好刷了。

**Comment by abc3660170** [comment]
WARP 是不是限速很明显，没有WARP之前FAST测速是200Mbps，WARP之后只有15Mbps

**Comment by fscarmen** [comment]
测试环境：
VPS：甲骨文 新加坡 ARM 2c 12g
系统: macOS Monterey 版本12.3.1(21E258)
浏览器: Chrome 版本 100.0.4896.127（正式版本） (x86_64)
宽带：广东移动 100兆小区宽带

<img width="1326" alt="image" src="https://user-images.githubusercontent.com/62703343/166086973-ddaac5a5-7111-4dd7-bcc0-7956a5ca19c1.png">
<img width="1362" alt="image" src="https://user-images.githubusercontent.com/62703343/166087694-90d6522d-3529-49fe-b0eb-11d55841e948.png">

**Comment by fscarmen** [comment]
> OK, 大佬，我来参照一下

补充了两个

**Comment by jackiehj** [comment]
新加坡还能刷到吗？刷了好久ip都没有解锁的

**Comment by fscarmen** [comment]
> 新加坡还能刷到吗？刷了好久ip都没有解锁的

估计短时间内不行了

**Comment by jackiehj** [comment]
> > 新加坡还能刷到吗？刷了好久ip都没有解锁的
> 
> 估计短时间内不行了

好吧。刚抢到甲骨文实例 - -！

**Comment by fscarmen** [comment]
> 
> 好吧。刚抢到甲骨文实例 - -！

恭喜，甲骨文新加坡不用warp解锁，原生 ip 多数能解锁的

**Comment by jackiehj** [comment]
> > 好吧。刚抢到甲骨文实例 - -！
> 
> 恭喜，甲骨文新加坡不用warp解锁，原生 ip 多数能解锁的

哈哈，刚试了下。确实原生 ip 就能解锁了！谢谢大佬 那就等万一 ip 被封了再用 warp 吧

**Comment by fscarmen** [comment]
哈哈，不戴套的感觉爽多了

**Comment by markosc** [comment]
可以添加國家西班牙

**Comment by fscarmen** [comment]
> 可以添加國家西班牙

不太明白意思啊，脚本有要求输入的地方啊，你输入西班牙不就好了？
