### ISSUE TITLE
Warp unlock with ¿"smart dns"?

### ISSUE THREAD

**Issue by markosc** [fscarmen/warp_unlock#16]
it will be possible in the future to integrate the "smart dns" option as this project does on github
https://github.com/ab77/netflix-proxy
thanks

**Comment by fscarmen** [comment]
As I understand netflix proxy is unlocked by unlocking the vps as a server and the client makes the proxy service it provides. 
If that is the case, we will not be able to change anything on the server side from the client side. 
Please elaborate on how smart dns works, and what you think.
thanks

**Comment by markosc** [comment]
The project does not use a client such as wireguard or openvpn, you only need to change the DNS of any device, be it smartphone or television, for the IP address of the vps, it already unblocks netflix content (uses ipv6) for this purpose

**Comment by fscarmen** [comment]
My understanding is as follows: Two VPS A and B---A can be unlocked Netflix, but B cannot.
A installs the project, and then adds B's IP to the generated web page for authorization. B set the DNS nameserver to A.
Then you want to watch Netflix -> make a request to B -> B detects that you want to request Netflix -> request A -> A request data from Netflix and reverse it to B-> B data back -> you see Netflix

So i call A being dns proxy server and B is a client (does not use a client. Just set the dns is ok).

It 's another way to unlock Netflix---DNS proxy. 
My project replace the warp ip to unlock. It is only needs to be completed in one VPS, and the server A is Cloudflare.
So i have no idea what i can do for the [netflix-proxy](https://github.com/ab77/netflix-proxy)
