### ISSUE TITLE
没有指定的 WARP 方式

### ISSUE THREAD

**Issue by CosmosLibra** [fscarmen/warp_unlock#17]
使用示例命令 
_bash <(curl -sSL https://raw.githubusercontent.com/fscarmen/warp_unlock/main/unlock.sh) -C -A us -4 -N n -M 1_
提示 没有指定的 WARP 方式

**Comment by fscarmen** [comment]
应该是你没有 warp ipv4 的，你可以去掉所有的参数，直接运行，脚本会智能判断你安装了什么 warp 方案的
```
bash <(curl -sSL https://raw.githubusercontent.com/fscarmen/warp_unlock/main/unlock.sh) -C -A us -4 -N n -M 1
```
