### ISSUE TITLE
关于增加telegram_bot通知解锁状态的提议 -【结论：2022.1.31 1.04 1. Support push the logs to Telegram. 1. 日志结果输出到 Telegram.】

### ISSUE THREAD

**Issue by ben-august** [fscarmen/warp_unlock#2]
感谢大佬的脚本。想提个建议，能不能考虑加个配置telegram_bot通知（或其他形式的通知），解锁失败了发通知，然后自动刷ip刷成功了再通知。要是一定时间间隔后（比如10分钟）还没收到刷ip成功的通知，那我考虑人工介入。因为不成功的话一直刷ip，可能会影响到wgcf用作代理的使用。

**Comment by fscarmen** [comment]
> 感谢大佬的脚本。想提个建议，能不能考虑加个配置telegram_bot通知（或其他形式的通知），解锁失败了发通知，然后自动刷ip刷成功了再通知。

哈哈，很久之前想到过。但我现在还完全不会 TG_bot 的搭建，日志如何输出到 bot，之前一直在完善 WARP 主脚本和新建解锁项目 。还没有时间研究，但我尝试学习一下。

> 因为不成功的话一直刷ip，可能会影响到wgcf用作代理的使用。

解决方案有以下两种：1、在协议层，使用 socks5 方案，脚本有提供。在 vps 搭建一个 warp socks5 代理，同时在代理outbound文件把奈飞流量分流过去，其他流量还是走原来 IPv4 出去。这样像换 socks5 IP 的话，不影响其他使用的。

2、在应用层，把奈飞代理从主代理那独立出来，用 clash , QX, loon 等作分流

**Comment by ben-august** [comment]
主要是我全走的warp了（也许感觉快一些些？）哈哈哈，不是单纯Netflix分流了

**Comment by ben-august** [comment]
我记得很久之前我用过一个telegram bot就是实现这个通知的 我找找

**Comment by fscarmen** [comment]
好的，谢谢！

**Comment by ben-august** [comment]
> 我记得很久之前我用过一个telegram bot就是实现这个通知的 我找找

https://github.com/yxkumad/streammonkeylite

https://coderfan.net/how-to-use-telegram-bot-to-alarm-you-when-someone-login-into-your-vps.html

**Comment by fscarmen** [comment]
我自己找了个，好像能用，哈哈
![image](https://user-images.githubusercontent.com/62703343/151738358-a52a9ca4-08d7-42b7-af8d-d755051b770b.png)

**Comment by ben-august** [comment]
> 我自己找了个，好像能用，哈哈 ![image](https://user-images.githubusercontent.com/62703343/151738358-a52a9ca4-08d7-42b7-af8d-d755051b770b.png)

期待大佬新版本上线

**Comment by fscarmen** [comment]
![image](https://user-images.githubusercontent.com/62703343/151741159-c4a2c8d0-642c-4521-b5a3-0884ef5b4e90.png)

**Comment by fscarmen** [comment]
> 期待大佬新版本上线

2022.1.31 1.04 1. Support push the logs to Telegram. 1. 日志结果输出到 Telegram.

先实现通知功能，之后再完善细节，即是中间过程考虑不输出了，只有状态变化的时候输出
