### ISSUE TITLE
【bug】【wgcf设备文件资源泄露】刷ip会导致run/udev/data磁盘空间占用一直增加-【结论: 由于其他原因导致，非本项目的问题，谢谢用户反馈】

### ISSUE THREAD

**Issue by kolychen** [fscarmen/warp_unlock#26]
环境：centos 7
刷ip就是不断和cf拨号连接，成功后会创建一个网卡设备，相关信息会写入  /run/udev/data目录中，断开连接后，这个资源没有正确释放，若一直不停刷ip，这个空间很快就会占满，从而导致其他依赖此空间的进程挂掉

**Comment by kolychen** [comment]
![image](https://user-images.githubusercontent.com/12987513/194705323-6ebaf859-fdf9-4c06-a3d3-f0529600a84a.png)

**Comment by fscarmen** [comment]
感谢你的使用和反馈，请问该磁盘空间主要作用是什么的？一般多大？会有些什么其他依赖也要用？ubuntu 和 debian也有这个空间吗？
我看到很多n开头的文件，都是刷ip出来的吗？
要处理这个也十分容易的，刷的时候一并把生成的文件删除可以了。

**Comment by fscarmen** [comment]
` grep -r 'wgcf' /run/udev/data/` 查查哪些文件包含了 wgcf 的内容，
我在 Debian 10 和 ubuntu 20.04 上试，发现一直会有一个文件，文件名以n开头，每次刷，后面的数字都加增加，但一直只有一个文件，没有像你说的不停增加。所以你上面的指令看看同时有哪些文件相关的。

<img width="788" alt="image" src="https://user-images.githubusercontent.com/62703343/194710535-204a81ab-cba3-4a59-9443-1a94e987c85a.png">

**Comment by fscarmen** [comment]
刚刚又在 GCP 开了一台 CentOS7 的机器，每10秒查一次 /run/udev/data/ 下有多少个文件含有关键字 wgcf ，都是只有一个，而且情况与 Debian 和 Ubuntu 测出来一样，文件名是n开关+后面的数字不断增大，但都是同一时间只存在一个这样的文件

<img width="642" alt="image" src="https://user-images.githubusercontent.com/62703343/194743053-69d93b3c-3ace-4c71-b257-b09288de1729.png">

**Comment by kolychen** [comment]
可能是我wgtools工具问题，这个工具是我手动下载的包安装的(之前脚本安装有点问题)，用systemctl 关闭wg会报错没有彻底关闭

发自我的iPhone

**Comment by fscarmen** [comment]
> 可能是我wgtools工具问题，这个工具是我手动下载的包安装的(之前脚本安装有点问题)，用systemctl 关闭wg会报错没有彻底关闭 发自我的iPhone
> […](#)
> 在 2022年10月9日，15:13，fscarmen ***@***.***> 写道： ﻿ 刚刚又在 GCP 开了一台 CentOS7 的机器，每10秒查一次 /run/udev/data/ 下有多少个文件含有关键字 wgcf ，都是只有一个，而且情况与 Debian 和 Ubuntu 测出来一样，文件名是n开关+后面的数字不断增大，但都是同一时间只存在一个这样的文件 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.

那是与本项目无关了？

**Comment by kolychen** [comment]
嗯，可以关闭

发自我的iPhone
