### ISSUE TITLE
docker方式部署的sock5代理IP变更导致的无法连接

### ISSUE THREAD

**Issue by styxiik** [fscarmen/warp_unlock#34]
背景：docker方式部署，xray使用docker的sock5作为outbound
问题：由于docker容器可能重启，VPS机器也会不时重启，重启时如果docker不止一个容器，sock5 ip可能会变更，比如原本脚本ip是172.17.0.2，重启后可能会变更为172.17.0.3，导致需要手动调整xray的outbound配置，对于我全部流量都走warp就会导致断网
解决建议：能否在docker的启动参数中加入“ --net bridge --ip 172.17.0.10”达到固定ip的作用

**Comment by fscarmen** [comment]
--net bridge 我记得是默认的，不用加都可以
--ip 这里可能弄一个新的段，比如 172.18.0.10。我考虑到的情况是，用户安装的时候，172.17.0.10 已经有相应的容器了。还不如新建一个段出来

**Comment by styxiik** [comment]
> --net bridge 我记得是默认的，不用加都可以 --ip 这里可能弄一个新的段，比如 172.18.0.10。我考虑到的情况是，用户安装的时候，172.17.0.10 已经有相应的容器了。还不如新建一个段出来

也是因为考虑到固定ip可能会有容器占用，所以原建议的ip靠后一些，新建一个段也可以确保没有占用。

**Comment by fscarmen** [comment]
试了一下，不能用原来的段创建，如果加入 --net bridge --ip 172.17.0.10 ，则显示 "docker: Error response from daemon: user specified IP address is supported on user defined networks only."

如果需要新的IP段，则要先创建 docker network create --subnet=172.18.0.0/16 wgcf，这样 --net wgcf --ip 172.18.0.18 就可以，但卸载的时候该 docker 网络也要手动删除，一般玩家不会呢

```
root@saopaulo2:~# curl -sx socks5h://172.18.0.18:40000 ip.gs
104.28.230.103
root@saopaulo2:~# docker network ls
NETWORK ID     NAME      DRIVER    SCOPE
96325b123727   bridge    bridge    local
3f56363f840e   host      host      local
bc5788deeebe   none      null      local
1e87799afb60   wgcf      bridge    local
```

**Comment by styxiik** [comment]
看来除非脚本增加uninstall，暂时我自己写了cron对xray的config进行sed可以提升稳定性，thanks!

**Comment by styxiik** [comment]
> 你可以像我一样新增一下网段 172.18. 并命名为 wgcf `docker network create --subnet=172.18.0.0/16 wgcf` 并用这里的文件 [docker.sh.zip](https://github.com/fscarmen/warp_unlock/files/9920934/docker.sh.zip)
> 
> 卸载
> 
> ```
> docker rm -f wgcf
> docker rmi fscarmen/netflix_unlock
> docker network rm wgcf
> rm -rf /etc/wireguard /usr/local/bin/wgcf
> ```
> 
> 我没有做卸载部分，想着能用docker并v2ray分流的，直接删除容器和镜像应该小儿科 :)

谢谢！

**Comment by fscarmen** [comment]
找个时间弄个卸载功能先
