### ISSUE TITLE
美国的vps ip刷不出来了

### ISSUE THREAD

**Issue by areyouokhaha** [fscarmen/warp_unlock#35]
感谢fscarmen的代码

**Comment by fscarmen** [comment]
> 感谢fscarmen的代码

感谢你的支持，我试了一下，最近 洛杉矶 和 拉斯维加斯 用 wgcf 不行，而且warp-go的双栈也不行，只能用 warp-go 的 WARP IPv6 才可以。而达拉斯则是正常。看来最近美国 VPS 的通病了。

**Comment by areyouokhaha** [comment]
我的是racknerd的，没开ipv6，不知道开了ipv6有用不

**Comment by fscarmen** [comment]
试试了，不过这样刷也只能刷 v6了，至于能不能刷到要看看，不同的地区真不一样，有的v4能刷，有的v6能刷

**Comment by areyouokhaha** [comment]
你好，久了我来回复一下，我解锁了非自制ip，原因是我从原先达拉斯服务器迁移到了圣何塞服务器，换了服务器和ip。后面用你这全脚本可以解锁了

**Comment by fscarmen** [comment]
也就是说原先的达拉斯怎么刷都不行，换到圣何塞就可以了？

**Comment by areyouokhaha** [comment]
再次感谢

**Comment by fscarmen** [comment]
感谢你的支持和积极反馈。如有问题请随时来提。
BTW，现在有的美国地区没有 warp 服务了，像 LA ，不知道什么恢复。

**Comment by areyouokhaha** [comment]
是的，这个问题我是从电报群中得知的，因为达拉斯的服务器太拉胯了，都这么反映，在我用达拉斯的时候，我用你这个脚本刷的少了一个两个安装步骤，昨天迁移了，用圣何塞的多了一个两个安装步骤，后面再用那个检测得知解锁非自制，美国，全程warp自动安装识别

**Comment by areyouokhaha** [comment]
达拉斯的ip是173开头的，圣何塞ip是23开头
