### ISSUE TITLE
解锁问题

### ISSUE THREAD

**Issue by ilikeboomboomboom** [fscarmen/warp_unlock#36]
ip刷出来说解锁但是我去检测却没解锁<!-![Screenshot_20221117_222137.jpg](https://user-images.githubusercontent.com/67816738/202472643-f4f41618-0a6c-458c-a833-954dcc73fe4a.jpg)

**Comment by fscarmen** [comment]
> ip刷出来说解锁但是我去检测却没解锁

你运行在非全局的模式，暂时没有看到有支持指定网络接口的检测脚本。说不解锁，他是用了你原生的 IP 了。

你也可以换成全局，再测就行了。

**Comment by ilikeboomboomboom** [comment]
请问非全局模式不是用来分流Netflix的吗，全局倒是没问题但是严重影响网速了。

**Comment by fscarmen** [comment]
> 请问非全局模式不是用来分流Netflix的吗，全局倒是没问题但是严重影响网速了。

你在 v2ray 配置文件里分流，把奈飞的流量指定到  WARP 的网络接口。

**Comment by areyouokhaha** [comment]
选1别选6
