### ISSUE TITLE
生成的脚本48行出现cb，运行时没找到这个命令

### ISSUE THREAD

**Issue by longmoon77** [fscarmen/warp_unlock#4]
系统：AlmaLinux 8.5 (类似RHEL 8.5)

中文，刷socks5 ip，用screen刷netflix时出现
```
/etc/wireguard/warp_unlock.sh: line 48: cb: command not found
```
然后查看了/etc/wireguard/warp_unlock.sh这个脚本发现第48行确实有一个cb命令，应该是个无效命令。

**Comment by fscarmen** [comment]
> 系统：AlmaLinux 8.5 (类似RHEL 8.5)
> 
> 中文，刷socks5 ip，用screen刷netflix时出现
> 
> ```
> /etc/wireguard/warp_unlock.sh: line 48: cb: command not found
> ```
> 
> 然后查看了/etc/wireguard/warp_unlock.sh这个脚本发现第48行确实有一个cb命令，应该是个无效命令。

谢谢你啊，已经去掉了，是失误弄进去的。

**Comment by longmoon77** [comment]
okay 3q
