### ISSUE TITLE
选择1刷新后 没有运行，也没有输入result.log

### ISSUE THREAD

**Issue by jinwyp** [fscarmen/warp_unlock#40]
貌似最近和warp-go 不兼容了。 不知道改了哪些东西

系统 AlmaLinux, centos, 8.7, 

1 使用你的脚本 用 https://github.com/fscarmen/warp  安装warp-go 后 , 然后选6刷新Netflix 直接显示 已经解锁 但程序卡住 没有正常退出

显示如下 
当前 Netflix 地区是:JP，需要解锁当前地区请按 y , 如需其他地址请输入两位地区简写 (如 hk ,sg，默认:JP):
 2023-01-22 22:50:11 区域 JP 解锁成功，IPv6: 2a09:bac1:3b40:120::16:19c 日本 Cloudflare，1 小时后重新测试，刷 IP 运行时长: 0 天 0 时 0 分 3 秒

然后程序一直卡住 没有正常退出 . 而且实际用其他脚本测试 并没有解锁非自制剧。 

README 里面 的 bash <(curl -sSL https://raw.githubusercontent.com/fscarmen/tools/main/warp_crontab.sh)
地址也是错误的

2 用本项目 之前可以正常运行 最近一个月 选择 1 crontab模式  脚本貌似没有运行 ， 同时也没有输出 /root/result.log 
手动运行 bash /usr/bin/warp_unlock.sh 也没有任何输出 /root/result.log  （这里最好能把日志输出到命令行 否则不知道什么问题）

/usr/bin/warp_unlock.sh 是正常存在的

3 crontab 模式好像修改的是 /etc/crontab 文件 。 但不同系统默认不是这个位置， 例如debian是 /var/spool/cron/crontabs/. 
直接修改 /etc/crontab 好像并不能立即生效

添加 crontab 可以用
crontab -l | { cat; echo "0 0 0 0 0 some entry"; } | crontab -

(crontab -l ; echo "0 * * * * your_command") | sort - | uniq - | crontab -

https://stackoverflow.com/questions/4880290/how-do-i-create-a-crontab-through-a-script
https://stackoverflow.com/questions/610839/how-can-i-programmatically-create-a-new-cron-job

总结问题就是刷新Netflix 脚本目前运行有问题， 没有正常运行。

**Comment by fscarmen** [comment]
> 然后程序一直卡住 没有正常退出 . 而且实际用其他脚本测试 并没有解锁非自制剧。

这里的卡着应该是一小时后重新测，不会退出的，所以你应该在 screen 下运行，又或者用本项目。我是根据 luoxue 和 lmc999 的脚本来改的，或许最近规则有所变化了。实际你还得用 v2ray/xray把奈飞分流过去 warp ipv6 看看。

> 选择 1 crontab模式 脚本貌似没有运行 ， 同时也没有输出 /root/result.log
这个模式是 5分 10分 15分 20分 这样运行的，因为定时任务的关系。所以不是一操作完马上有日志的，你要到下一个5分钟的倍数看结果 `tail -f result.log`

3
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/62703343/214003817-f595c026-7b5c-4e60-b771-fdf474be920c.png">
