### ISSUE TITLE
Provide license key to docker image

### ISSUE THREAD

**Issue by SayidHosseini** [fscarmen/warp_unlock#46]
Hi there 

I'd like to know if there is a way (even a workaround) to provide license key to the Docker image.

**Comment by fscarmen** [comment]
Edit the shell file before install . https://github.com/fscarmen/warp_unlock/blob/main/docker.sh#L163 to `rm -rf /usr/local/bin/wgcf`

login the docker: `docker exec -it wgcf bash`

Change your license key in the account file : `./wgcf-account.toml`

Update your acoount : `wgcf update --name unlock --config ./wgcf-account.toml`

Generate : ` wgcf generate --config ./wgcf-account.toml --profile ./wgcf-new.conf

`wg-quick down wgcf `

Change the private key and ipv6 in wgcf.conf from the file : ./wgcf-new.conf

`wgcf-quick up wgcf`

**Comment by SayidHosseini** [comment]
Thank you!
That worked.

I modified the `docker.sh` file to mount the `wgcf-new.conf` in the container `/etc/wireguard/wgcf.conf` to persist the changes.
