### ISSUE TITLE
Unlocking Netflix not working any more

### ISSUE THREAD

**Issue by SayidHosseini** [fscarmen/warp_unlock#47]
Hi

I've been using your scripts for some time, and they were ok. However, couple of days ago, it stopped unlocking Netflix with status "No 😰".

At first, I thought it was a bandwidth limitation and tried applying a license, but unfortunately that is not the case. I tried the script on multiple servers from several datacenters and no lock.

Am I doing something wrong or is there a problem?

**Comment by fscarmen** [comment]
Nothing to do these days. I will have a check this weekend.

**Comment by SayidHosseini** [comment]
Hello there,
This (https://github.com/fscarmen/warp_unlock/issues/49) issue seems to be the same as mine.

Have you had any chance to try this out? I'm mainly using the docker image.

**Comment by fscarmen** [comment]
I have updated the scripts and images right now. We need reinstall.

**Comment by SayidHosseini** [comment]
It's fixed.
Thanks a lot!
