### ISSUE TITLE
没有指定的warp方式

### ISSUE THREAD

**Issue by learnman1994** [fscarmen/warp_unlock#48]
vps已经手动配置过warp了，v2ray配置了分流，解锁了奶粉，但是没有解锁迪士尼，所以想通过你的脚本更换一个IP，但是运行脚本却提示这个。

**Comment by fscarmen** [comment]
你应该是手动安装warp或者使用其他作者的warp脚本，请更换为我的，应该就能解决问题
https://github.com/fscarmen/warp

**Comment by fscarmen** [comment]
问题解决了吗？

**Comment by learnman1994** [comment]
> 问题解决了吗？

谢谢你，问题已经解决了。
