### ISSUE TITLE
warp脚本的奈飞解锁功能一直显示NO

### ISSUE THREAD

**Issue by Rockeeeer** [fscarmen/warp_unlock#49]
![2](https://user-images.githubusercontent.com/89590960/227730059-7df54c5d-d01d-4a5c-816d-032d254782b6.png)
![1](https://user-images.githubusercontent.com/89590960/227730088-ccfeeaec-5bde-40e7-b575-9d5ddbd766f7.png)
![3](https://user-images.githubusercontent.com/89590960/227730090-5af8f1eb-a34e-4548-9ac0-e2dfec0d7314.png)

作者你好，
最近解锁奈飞的脚本好像出了点问题

解锁可以分为选项6和选项11
1：如果选择6，解锁奈飞的IP可以在几次内解锁成功，并且验证确实解锁成功了，成功率非常高。
2：选择11，无论在里面选择模式1或者模式2（其他模式没用过），一直一直显示NO，最近一直没有YES过，我以为自己的VPS的问题，换了好几个地区都一样。
3：模式11刷IP的过程中，部分IP显示解锁NO，但通过其他方式验证，实际上这个IP是解锁了的。
4：小白私心请教个问题，如果选择选项6，解锁奈飞成功后，我ctrl+c退出了当前脚本，那这个脚本会在后台1小时后继续执行解锁任务？还是被我ctrl+c彻底关掉停止工作了了？我哪天需要解锁的时候又得再手动去解锁一次吗？

**Comment by fscarmen** [comment]
1.我要看看选项6和11之间有什么差异了，做了太久了，判断方法是一样的，只是判断的节点可能会有不同，我这几天看看。
2.同1
3.同1
4.ctrl+c是关掉不刷，如果你关掉的时候正好是连着warp的，就有warp，如果刚好在关了的时候，就没有warp而是原生的出口。
现在你说选项6现在比较准，你可以在 screen 会话模式后，后台不停的运行，这样即使你退出ssh，也仍然工作。

**Comment by Rockeeeer** [comment]
![1](https://user-images.githubusercontent.com/89590960/227759579-23122a75-1f45-455a-a3b6-a3f881dea907.png)

作者你好，感谢你如此耐心回复我
刚才看到脚本更新了，所以赶紧更新了一下，测试了一下奈飞解锁的选项6和选项11。
1：一台新加坡AWS,一台美国洛杉矶VPS，warp-go1.1.3新脚本都测试了
2：选项6，脚本显示奈飞解锁成功，实际上并没有解锁，如上图。
3：选项11，还是一样的问题，刷奈飞IP的过程中一直显示NO，但是IP确是解锁的，所以脚本一直不停的运转中。

**Comment by fscarmen** [comment]
现在还没有完全更新完，项目11的还没有处理好，正在处理，等下回复你

**Comment by Rockeeeer** [comment]
好的谢谢，更新好以后我会第一时间测试一下。
我有一台香港的VPS，试了好几个作者的warp脚本，无论是wgcf，warp-go，warp cli，都安装不上，
只有你这个脚本的warp-go脚本一次性就安装上了，并且附带了奈飞解锁的功能，完美解决了我的所有需求。

**Comment by fscarmen** [comment]
更新好了，首先，无论是 [wgcf / warp-go](https://github.com/fscarmen/warp) 和 [warp_unlock](https://github.com/fscarmen/warp_unlock) 项目奈飞的解锁检测方法是使用 lmc999 的检测脚本改过来的，项目地址：https://github.com/lmc999/RegionRestrictionCheck

之前出问题是因为上游的 lmc999 从2023年3月4日开始多加了个检测源，Netflix Detection:使用多个片源以支持更多地区 Pakistan等，https://github.com/lmc999/RegionRestrictionCheck/commit/449b778c49633db25a362e571239335948354345

我已经做了相关的处理，一样使用两个检测源。


> 2：选项6，脚本显示奈飞解锁成功，实际上并没有解锁，如上图。

你使用的 nf 的程序我没有用过，也没有了解过他如何检测解锁状态的。你可以试试用 lmc999 的再测一下

> 3：选项11，还是一样的问题，刷奈飞IP的过程中一直显示NO，但是IP确是解锁的，所以脚本一直不停的运转中。

刚刚也更新了

> 4：私心再问个问题，warp普通账号，warp+账号，warp Teams(Zero Trust)账号，这3种账号哪种速度最快，解锁奈飞的成功率最高？

奈飞不是托管在 Cloudflare ，对于非 CF 的网站，应该是没有速度之分的，至于成功率，暂时没有做这个研究，但暂时没有证据说明有差别，所以我理解都是一样的。

**Comment by Rockeeeer** [comment]
![1](https://user-images.githubusercontent.com/89590960/227771644-66406edf-5b6b-4dca-b4b7-815490423d0a.png)
![2](https://user-images.githubusercontent.com/89590960/227771647-94a09e38-2fcf-4e19-b351-62cfb36177b9.png)

我测试了一下
1：同一个IPv6地址，选项6显示解锁成功，其他途径测试解锁不成功，包括lmc999的测试脚本，用选项11也看到了这个ip解锁不成功。
2：选项11终于正常了，太棒了！！
谢谢作者

**Comment by fscarmen** [comment]
> 1：同一个IPv6地址，选项6显示解锁成功，其他途径测试解锁不成功，包括lmc999的测试脚本，用选项11也看到了这个ip解锁不成功。

我的方法都是按照他来的，应该不可能不一致。妆下次与lmc999结果显示不一致，最好给个ssh我进去判断一下

**Comment by Rockeeeer** [comment]
18.163.189.25
root
123456
新开的，什么都没安装，你测试一下试试

**Comment by fscarmen** [comment]
I need update the scripts . Please 

> 123456

我现在才看到，已经登陆不了了，方便你tg @fscarmen2 告诉我，我主要想看看和 lmc999 的在判断上还为什么会有差异。
