### ISSUE TITLE
怎么卸载完了ip改不回原来的ip

### ISSUE THREAD

**Issue by micro-stone** [fscarmen/warp_unlock#5]

**Comment by fscarmen** [comment]
脚本运行的机制是卸载完了，会重新获取一次IP。

原因是用户有可能卸载的时候正好换IP，如果不重新获取，可能在中间阶段，这样会导致网络有问题的，至于 WARP 的 IP 获取是随机的，不能指定。

**Comment by kivid** [comment]
遇到过，reboot好了

**Comment by fscarmen** [comment]
> 遇到过，reboot好了

我理解错意思了，我还以为卸载刷 ip 脚本，仍然需要保留卸载前的那个 WARP IP。如果是原生的 IP 查不到，可以找找其他原因，具体问题具体分析了，实在不行，就 reboot ，但我担心问题未找到， reboot 也不一定行：）
