### ISSUE TITLE
能定时更换warp ip，但是不需要解锁流媒体吗

### ISSUE THREAD

**Issue by sakz** [fscarmen/warp_unlock#53]
因为目的是解锁chatgpt，一直用同一个ip会被限制

**Comment by fscarmen** [comment]
做个定时服务，定时开关一次warp可以啦。其实我建议你用warp ipv6，这个ip多，应该不用换，能长期使用。

**Comment by sakz** [comment]
> 做个定时服务，定时开关一次warp可以啦。其实我建议你用warp ipv6，这个ip多，应该不用换，能长期使用。

好像来来去去都是2个IP

 WireProxy 已连接
 本地 Socks5: 127.0.0.1:40000
 WARP free IPv4: 104.28.201.73 美国 Cloudflare
[root@test ~]# warp y
 已断开 WirePorxy，再次连接可以用 warp y
[root@test ~]# warp y
 WireProxy 已连接
 本地 Socks5: 127.0.0.1:40000
 WARP free IPv4: 104.28.201.73 美国 Cloudflare
[root@test ~]# warp y
 已断开 WirePorxy，再次连接可以用 warp y
You have new mail in /var/spool/mail/root
[root@test ~]# warp y
 WireProxy 已连接
 本地 Socks5: 127.0.0.1:40000
 WARP free IPv4: 104.28.233.73 美国 Cloudflare
[root@test ~]# warp y
 已断开 WirePorxy，再次连接可以用 warp y
[root@test ~]# warp y
 WireProxy 已连接
 本地 Socks5: 127.0.0.1:40000
 WARP free IPv4:
[root@test ~]# warp y
 已断开 WirePorxy，再次连接可以用 warp y
[root@test ~]# warp y
 WireProxy 已连接
 本地 Socks5: 127.0.0.1:40000
 WARP free IPv4: 104.28.233.73 美国 Cloudflare
[root@test ~]# warp y
 已断开 WirePorxy，再次连接可以用 warp y
You have new mail in /var/spool/mail/root
[root@test ~]# warp y
 WireProxy 已连接
 本地 Socks5: 127.0.0.1:40000
 WARP free IPv4: 104.28.201.73 美国 Cloudflare
[root@test ~]# warp y
 已断开 WirePorxy，再次连接可以用 warp y
[root@test ~]# warp y
 WireProxy 已连接
 本地 Socks5: 127.0.0.1:40000
 WARP free IPv4: 104.28.233.73 美国 Cloudflare

**Comment by fscarmen** [comment]
无计了，用 ipv6 ，xray里做好分流

**Comment by sakz** [comment]
> 无计了，用 ipv6 ，xray里做好分流

可以在配置文件指定warp IPv4地址吗

**Comment by sakz** [comment]
因为我发现在一个固定的vps上`warp i`刷ip来来去去都是那两三个IP
