### ISSUE TITLE
使用ipv4优先解锁netflix，warp接管ipv4流量后vps上kcptun无法正常串联ss服务端

### ISSUE THREAD

**Issue by ukwang1982** [fscarmen/warp_unlock#6]
一台vps上部署了ss服务端，并且串联了kcptun进行加速，不启动warp则串联加速正常。warp启动以后vps上的kcptun就无法成功串联ss服务端了，但是直连ss则是正常的，经过ss代理后的ip为warp ip。请问下这个如何解决呢？

**Comment by fscarmen** [comment]
抱歉对kcptun不了解。我自己在GCP上用ss+warp使用的，如你找到解决方案还望你教教

**Comment by ukwang1982** [comment]
> 请问你是如何解决的呢？

这个问题应该无解了，放弃了

**Comment by fscarmen** [comment]
正在弄一个更好玩的，谢谢你的关注
