### ISSUE TITLE
解锁奈飞，定时5分钟检查一次,遇到不解锁时更换 WARP IP，直至刷成功。 启动时提示需要升级cron，然后报错

### ISSUE THREAD

**Issue by liangfengshan** [fscarmen/warp_unlock#67]
<img width="968" alt="image" src="https://github.com/fscarmen/warp_unlock/assets/35560294/2dbba118-2854-4c42-bd4e-c5bf99b6d7e9">

这是什么原因，我有两个服务器都是提示这个。

**Comment by liangfengshan** [comment]
> 

是centos7

**Comment by fscarmen** [comment]
c7有点古老，我没有详细测试，可以的话，你试试换个deian 10 或者 ubuntu 20.04 以上的

**Comment by liangfengshan** [comment]
好的谢谢
