### ISSUE TITLE
关于更换地区

### ISSUE THREAD

**Issue by SakenTam** [fscarmen/warp_unlock#7]
VPS是【US】，在选择地区是选择其他如【JP】，更换地区时则会一直刷到【US】地区的IP且一直解锁失败，请问一下目前是只能选择VPS所在的地区吗

**Comment by fscarmen** [comment]
机制是这样的，至于为什么会弄个地区出来出大家填呢，原因是有的地方，比如新加坡，一会儿刷出新加坡，一会儿又会刷出美国，为了限制一定要是新加坡，所以加个地区的限制。
除这个情况外，都是vps原生ip是哪，warp就分配那，Netfilx认定的解锁区域就是那。
