### ISSUE TITLE
Docker中检查脚本不能正常运行

### ISSUE THREAD

**Issue by ukid** [fscarmen/warp_unlock#8]
进入容器后
````
PID   USER     TIME  COMMAND
    1 root      0:00 {busybox} ash ./run.sh
   89 root      0:00 crond
   90 root      0:02 ./gost -L :40000
 1443 root      0:00 bash
10055 root      0:00 ps aux
````

手工执行bash /etc/wireguard/warp_unlock.sh

1.行11.
找不到timedatectl set-timezone Asia/Shanghai

2.行12.
判断进不去.
$(pgrep -laf ^[/d]*bash.*warp_unlock | awk -F, '{a[$2]++}END{for (i in a) print i" "a[i]}')
打印结果为3

**Comment by fscarmen** [comment]
> 1.行11.
> 找不到timedatectl set-timezone Asia/Shanghai

这行可以不要了，我稍后更新一下，没有也不会影响的，这个作用是显示北京时间，我已经在另外一处处理了。

> 2.行12.
> 判断进不去.
> $(pgrep -laf ^[/d]*bash.*warp_unlock | awk -F, '{a[$2]++}END{for (i in a) print i" "a[i]}')
> 打印结果为3

这个是正常的，说明正在刷了。这个作用是脚本自锁。具体说，因为脚本是5分钟检测一次，不解锁就运行的 。如果不加这个自锁的情况下，第1个5分钟检测运行，过了5分钟仍然未找到适合的ip，第2个检测又来，又再运行脚本，这样就会存在两个刷的脚本在运行了会出问题的。加这个就是第2个5分钟运行的时候发现进程里已经有在运行中了，就不作任何处理了。

你可以通过以下两个方式判断一下工作状态，容器内 ```ps -T | grep warp```或```pgrep -laf warp```

判断现在的IP是否在变```curl -ks4m5 ip.gs```，这个要有间隔的进去看

**Comment by ukid** [comment]
感谢您的回复！

我也奇怪呢，我有一台美国机器，确实有收到电报消息，排除完全不能用。
````
bash-5.1# ps -T | grep warp
11882 root      0:00 grep warp
bash-5.1# pgrep -laf warp
bash-5.1# bash /etc/wireguard/warp_unlock.sh 
3
````
$(pgrep -laf ^[/d]*bash.*warp_unlock | awk -F, '{a[$2]++}END{for (i in a) print i" "a[i]}')
打印结果为3

是否能加上点日志输出方便诊断？多谢🙏

**Comment by ukid** [comment]
更多日志
````
root@VPS12155434:~# docker exec -it wgcf bash
bash-5.1# curl -ks4m5 ip.gs
8.31.163.75
bash-5.1# cat status.log 
null
bash-5.1# crontab -l
# do daily/weekly/monthly maintenance
# min   hour    day     month   weekday command
*/15    *       *       *       *       run-parts /etc/periodic/15min
0       *       *       *       *       run-parts /etc/periodic/hourly
0       2       *       *       *       run-parts /etc/periodic/daily
0       3       *       *       6       run-parts /etc/periodic/weekly
0       5       1       *       *       run-parts /etc/periodic/monthly

*/5 * * * * nohup bash /etc/wireguard/warp_unlock.sh >/dev/null 2>&1 &
bash-5.1# date
Wed Mar  2 13:36:56 CST 2022
bash-5.1# date
Wed Mar  2 13:42:26 CST 2022
bash-5.1# cat status.log 
null
````

**Comment by ukid** [comment]
看时间已经过了5分钟了呢，到目前时间点
````
bash-5.1# date
Wed Mar  2 13:52:48 CST 2022
bash-5.1# cat status.log 
nul
````

**Comment by ukid** [comment]
好吧，我先不使用docker了，等待其他用户反馈🙏

**Comment by aguero119** [comment]
这玩意儿这么卸载?

**Comment by fscarmen** [comment]
docker 吗？
```docker rm -f wgcf```
