### ISSUE TITLE
更改ip

### ISSUE THREAD

**Issue by demianrey** [fscarmen/warp_unlock#9]
如果可行，请更改区域IP？ 它总是让我失败，问候和感谢这个工具
![image](https://user-images.githubusercontent.com/48655207/156828315-7114c396-8187-48d2-81be-41de0edd32b6.png)

**Comment by fscarmen** [comment]
感谢你的支持，从结果来看，你这台vps是美国IP，只能刷美国的，你改为日本是不可能刷出来的

**Comment by demianrey** [comment]
OOO 这就是它的工作原理，我有一个带有墨西哥 IP 的服务器，我在该地区写 MX 但它也不起作用
![image](https://user-images.githubusercontent.com/48655207/156830338-c427eebd-ef20-4450-8eb8-1dec13f12e5c.png)
你知道是否有 cloudflare warp 区域列表?

问候并感谢您的及时回复

**Comment by fscarmen** [comment]
You can refer to this : https://www.cloudflarestatus.com/
Why didn't you have a try with US?

**Comment by demianrey** [comment]
actually the region I am looking for is Mexico or one of Latin America, Netflix offers other content.... the page you provided me shows Mexico
![image](https://user-images.githubusercontent.com/48655207/156833046-89480a99-62ce-4add-b99b-3c32e77eca1d.png)

**Comment by fscarmen** [comment]
> actually the region I am looking for is Mexico or one of Latin America, Netflix offers other content.... the page you provided me shows Mexico .

The WARP IP is allocated nearby, that is, the native American can only arrange the WARP IP of the United States. Letting the user enter the desired region is to prevent some places from changing, such as Singapore, sometimes Singapore, and sometimes the United States.

**Comment by demianrey** [comment]
thank you very much I already understood how it works, its main purpose is to show all the content of netflix and not only the original
